# ---
# # Forcing Kubelet metrics scraping on http 
# kubelet:
#   enabled: true
#   serviceMonitor:
#     https: false
# # Disabling scraping of Master Nodes Components
# kubeControllerManager:
#   enabled: false
# kubeScheduler:
#   enabled: false
# kubeEtcd:
#   enabled: false
# kubeProxy:
#   enabled: false


---
defaultRules:
  rules:
    etcd: false
    kubeScheduler: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        prometheus: app
commonLabels:
  prometheus: app
grafana:
  adminPassword: wDNELtSPkP2BZFSn